version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  bitbucket:
    driver: local

services:
 artifactory:
  build: ./artifactory-oss
  hostname: artifactory
  ports:
    - "18081:8081"
  volumes:
    - /opt/artifactory:/var/opt/jfrog/artifactory
  networks:
    - prodnetwork

 jenkins:
  hostname: jenkins
  build: ./jenkins
  ports:
    - "18080:8080"
    - "50000:50000"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /opt/jenkins-data/:/var/jenkins_home
  depends_on:
    - artifactory
    - sonar
    - jmeter
    - bitbucket
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  hostname: sonar
  image: ambientdocker/docker-sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar

 sonardb:
  hostname: sonardb
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data

 jmeter:
  hostname: jmeter
  command: tail -f /dev/null
  networks:
    - prodnetwork
  build: ./jmeter
  volumes:
    - /opt/jmeter/results:/results
    - /opt/jmeter/scripts:/scripts

 bitbucket:
  hostname: bitbucket
  networks:
    - prodnetwork
  image: atlassian/bitbucket-server
  ports:
    - "7990:7990"
    - "7999:7999"
  volumes:
    -  bitbucket:/var/atlassian/application-data/bitbucket

 slave:
  hostname: slave
  networks:
    - prodnetwork
  build: ./slave
  environment:
   - SSH_USERPASS=password
  ports:
    - "2222:22"






